"""sentiment became nullable

Revision ID: 52cba65e6767
Revises: 89e82472075d
Create Date: 2022-11-13 13:44:05.209926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cba65e6767'
down_revision = '89e82472075d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'sentiment',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'sentiment',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
